### ISSUE TITLE
CB2 Silkscreen Error

### ISSUE THREAD

**Issue by mnaberez** [svenpetersen1965/PET_CBM_1541_Adapter#1]
There is silkscreen error shown in the photo below.  CB2 is incorrectly marked as CA2.

Note also that in this photo (from page 2 of [the PDF](https://github.com/svenpetersen1965/PET_CBM_1541_Adapter/blob/905ae55b180d998c0385b143dd996a1b26bb2d8f/Rev.%200/pdf/PET_1541_Ada_v0.pdf)), the pads for CB2 have been shorted.  This doesn't do anything.  Ideally, a future version of the PDF would show these pads as open.

![cb2-silkscreen-error](https://user-images.githubusercontent.com/52712/144726159-88bd00d3-e2a9-4999-ba82-489a761d8704.png)

![user-port](https://user-images.githubusercontent.com/52712/144726208-623c9a73-a10a-439a-b77f-8a055eac1b29.png)
See also the [schematic](http://zimmers.net/anonftp/pub/cbm/schematics/computers/pet/univ/8032081-03.gif).

**Comment by svenpetersen1965** [comment]
Thanks for the hint. I have fixed it (also in the schematics and the docs.
Regards,
Sven
